# Generated by Django 3.1.5 on 2021-03-11 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controlemomenten_gepland',
        ),
        migrations.AlterModelOptions(
            name='bedrijven',
            options={'verbose_name_plural': 'Bedrijven'},
        ),
        migrations.AlterModelOptions(
            name='vloeren',
            options={'verbose_name_plural': 'Vloeren'},
        ),
        migrations.AddField(
            model_name='vloeren',
            name='definitief_binnen_gepland',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vloeren',
            name='ter_eerste_controle_gepland',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vloeren',
            name='ter_eerste_controle_retour_binnen_gepland',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vloeren',
            name='ter_tweede_controle_gepland',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vloeren',
            name='ter_tweede_controle_retour_binnen_gepland',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
