# Generated by Django 3.1.5 on 2021-03-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210312_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datum_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vloeren',
            name='datum_document',
        ),
    ]
