# Generated by Django 3.1.5 on 2021-03-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_vloeren_bedrijfsnaam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vloeren',
            name='bedrijfsnaam',
        ),
    ]
