# Generated by Django 3.1.5 on 2021-03-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_vloeren_bedrijfsnaam'),
    ]

    operations = [
        migrations.AddField(
            model_name='vloeren',
            name='bedrijfsnaam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.bedrijven'),
            preserve_default=False,
        ),
    ]
