# Generated by Django 3.1.5 on 2021-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_vloeren_bedrijfsnaam'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlemomenten_gepland',
            name='vloeren',
            field=models.ManyToManyField(to='database.Vloeren'),
        ),
    ]
