# Generated by Django 3.1.7 on 2021-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_controlemomenten_gepland_vloeren'),
    ]

    operations = [
        migrations.AddField(
            model_name='datum_document',
            name='vloeren',
            field=models.ManyToManyField(to='database.Vloeren'),
        ),
    ]
