# Generated by Django 3.1.5 on 2021-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_datum_document_vloeren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum_document',
            name='vloeren',
        ),
        migrations.AddField(
            model_name='vloeren',
            name='datum',
            field=models.ManyToManyField(to='database.Datum_Document'),
        ),
    ]
