# Generated by Django 3.1.5 on 2021-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20210411_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vloeren',
            name='datum',
        ),
        migrations.AddField(
            model_name='datum_document',
            name='vloeren',
            field=models.ManyToManyField(to='database.Vloeren'),
        ),
    ]
