# Generated by Django 3.1.7 on 2021-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210411_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnummer', models.CharField(max_length=10)),
                ('projectnaam', models.CharField(max_length=30)),
                ('plaats', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlemomenten_gepland',
            name='vloeren',
        ),
        migrations.AddField(
            model_name='controlemomenten_gepland',
            name='datum_doc',
            field=models.ManyToManyField(to='database.Datum_Document'),
        ),
    ]
