# Generated by Django 3.1.7 on 2021-12-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20211202_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='vloeren',
            name='projectnaam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.projecten'),
        ),
    ]
