# Generated by Django 3.1.7 on 2022-01-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_vloeren_projectnaam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlemomenten_gepland',
            name='datum_doc',
        ),
        migrations.RemoveField(
            model_name='datum_document',
            name='vloeren',
        ),
        migrations.RemoveField(
            model_name='vloeren',
            name='bedrijfsnaam',
        ),
        migrations.RemoveField(
            model_name='vloeren',
            name='projectnaam',
        ),
        migrations.DeleteModel(
            name='Bedrijven',
        ),
        migrations.DeleteModel(
            name='Controlemomenten_gepland',
        ),
        migrations.DeleteModel(
            name='Datum_Document',
        ),
        migrations.DeleteModel(
            name='Projecten',
        ),
        migrations.DeleteModel(
            name='Vloeren',
        ),
    ]
