# Generated by Django 3.1.7 on 2022-01-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0014_auto_20220124_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrijven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Bedrijven',
            },
        ),
        migrations.CreateModel(
            name='Projecten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnummer', models.CharField(max_length=10)),
                ('projectnaam', models.CharField(max_length=30)),
                ('plaats', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vloeren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('documentnaam', models.CharField(max_length=50)),
                ('bedrijfsnaam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bedrijven')),
                ('projectnaam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.projecten')),
            ],
            options={
                'verbose_name_plural': 'Vloeren',
            },
        ),
        migrations.CreateModel(
            name='Datum_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('vloeren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vloeren')),
            ],
        ),
        migrations.CreateModel(
            name='Controlemomenten_gepland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ter_eerste_controle_gepland', models.DateField()),
                ('ter_eerste_controle_retour_binnen_gepland', models.DateField()),
                ('ter_tweede_controle_gepland', models.DateField()),
                ('ter_tweede_controle_retour_binnen_gepland', models.DateField()),
                ('definitief_binnen_gepland', models.DateField()),
                ('datum_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.datum_document')),
            ],
            options={
                'verbose_name_plural': 'Geplande controlemomenten',
            },
        ),
    ]
