# Generated by Django 4.1.7 on 2023-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_bedrijven_controlemomenten_gepland_datum_document_projecten_vloeren'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlemomenten_gepland',
            old_name='datum_doc',
            new_name='datum',
        ),
        migrations.AddField(
            model_name='vloeren',
            name='bestand',
            field=models.FileField(blank=True, null=True, upload_to='documenten/'),
        ),
        migrations.AlterField(
            model_name='bedrijven',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='controlemomenten_gepland',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datum_document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projecten',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vloeren',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
